EnableSound:
    LDA #$80
    LDX #LOW(music_music_data)
    LDY #HIGH(music_music_data)
    JSR FamiToneInit
	RTS

PlaySound:
    LDA #$00
    LDX #LOW(music_music_data)
    LDY #HIGH(music_music_data)
    JSR FamiToneMusicPlay
    RTS

;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $cd,$c8,$c1,$00,$02


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $80,$41,$4b,$4f,$41,$4b,$4f,$41,$4b,$51,$41,$4b,$51,$4f,$4b,$41
	.db $3d,$43,$33,$39,$43,$33,$39,$43,$37,$3d,$47,$37,$3d,$47,$37,$3d
	.db $48,$81
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref1:
	.db $f9,$85
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref2:
	.db $f9,$85
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref3:
	.db $f9,$85
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref4:
	.db $f9,$85
	.db $fd
	.dw .song0ch4loop
