;this file for FamiTone2 library generated by text2data tool

magnetizer_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $f0 ;instrument $00
	.dw .env1,.env0,.env8
	.db $00
	.db $f0 ;instrument $01
	.dw .env2,.env0,.env8
	.db $00
	.db $30 ;instrument $02
	.dw .env3,.env0,.env9
	.db $00
	.db $30 ;instrument $03
	.dw .env4,.env6,.env0
	.db $00
	.db $30 ;instrument $04
	.dw .env5,.env7,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $ca,$ca,$c7,$c7,$c6,$c5,$c3,$c2,$c2,$c1,$00,$09
.env2:
	.db $cf,$ce,$cd,$cc,$ca,$c7,$c4,$00,$06
.env3:
	.db $c4,$c6,$c7,$c7,$c5,$c3,$c3,$00,$06
.env4:
	.db $cf,$00,$00
.env5:
	.db $cb,$cc,$cc,$cb,$c9,$c5,$c4,$c2,$00,$07
.env6:
	.db $cc,$c0,$b9,$b6,$b3,$ae,$a8,$00,$06
.env7:
	.db $c0,$b4,$00,$01
.env8:
	.db $c0,$c1,$c1,$c0,$00,$00
.env9:
	.db $c0,$08,$be,$be,$c0,$00,$02


.song0ch0:
	.db $fb,$05
.song0ch0loop:
.ref0:
	.db $80,$21,$35,$39,$21,$35,$39,$21,$35,$39,$21,$35,$39,$3f,$39,$3f
	.db $42,$81
.ref1:
	.db $21,$35,$39,$21,$35,$39,$21,$35,$39,$21,$35,$39,$2f,$35,$2f,$2a
	.db $81
.ref2:
	.db $21,$35,$39,$21,$35,$39,$21,$35,$39,$21,$35,$39,$3f,$39,$3f,$42
	.db $81
.ref3:
	.db $21,$35,$39,$21,$35,$39,$21,$43,$47,$43,$35,$3d,$3f,$3d,$2b,$34
	.db $81
	.db $ff,$11
	.dw .ref2
	.db $ff,$11
	.dw .ref1
	.db $ff,$11
	.dw .ref2
	.db $ff,$11
	.dw .ref3
	.db $ff,$11
	.dw .ref2
	.db $ff,$11
	.dw .ref1
	.db $ff,$11
	.dw .ref2
	.db $ff,$11
	.dw .ref3
	.db $ff,$11
	.dw .ref2
	.db $ff,$11
	.dw .ref1
	.db $ff,$11
	.dw .ref2
	.db $ff,$11
	.dw .ref3
.ref16:
	.db $88,$5f,$21,$21,$4d,$13,$2b,$57,$21,$21,$00,$99
.ref17:
	.db $51,$2b,$21,$51,$21,$21,$57,$21,$1d,$21,$51,$21,$51,$21,$51,$2a
	.db $81
.ref18:
	.db $5f,$21,$21,$4d,$13,$2b,$57,$21,$21,$00,$95,$20,$81
.ref19:
	.db $51,$2b,$21,$51,$21,$21,$4d,$47,$43,$2f,$51,$17,$4d,$1d,$43,$2a
	.db $81
.ref20:
	.db $5f,$21,$21,$4d,$13,$2b,$57,$21,$21,$00,$99
	.db $ff,$11
	.dw .ref17
	.db $ff,$0d
	.dw .ref18
	.db $ff,$11
	.dw .ref19
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref24:
	.db $00,$bd
.ref25:
	.db $00,$bd
.ref26:
	.db $82,$39,$21,$09,$51,$1d,$09,$21,$09,$00,$9d
.ref27:
	.db $00,$bd
.ref28:
	.db $39,$21,$09,$51,$1d,$09,$21,$09,$00,$9d
.ref29:
	.db $00,$bd
.ref30:
	.db $39,$21,$09,$51,$1d,$09,$21,$09,$01,$84,$21,$39,$21,$39,$21,$38
	.db $83,$00
.ref31:
	.db $82,$39,$21,$09,$51,$1d,$09,$21,$09,$84,$2f,$43,$1d,$3d,$35,$01
	.db $43,$2a,$00
.ref32:
	.db $82,$39,$21,$09,$51,$1d,$09,$21,$09,$01,$84,$21,$39,$21,$39,$21
	.db $38,$83,$00
.ref33:
	.db $82,$39,$21,$09,$51,$1d,$09,$21,$09,$84,$21,$39,$3f,$21,$47,$01
	.db $39,$00,$81
	.db $ff,$11
	.dw .ref32
	.db $ff,$11
	.dw .ref31
	.db $ff,$11
	.dw .ref32
	.db $ff,$11
	.dw .ref33
	.db $ff,$11
	.dw .ref32
	.db $ff,$11
	.dw .ref31
.ref40:
	.db $88,$69,$00,$85,$5b,$00,$85,$5f,$00,$85,$84,$09,$21,$09,$21,$09
	.db $20,$83,$00
.ref41:
	.db $88,$5b,$00,$85,$57,$00,$85,$4d,$00,$89,$56,$85,$57,$01,$5b,$00
	.db $81
.ref42:
	.db $69,$00,$85,$6f,$00,$85,$69,$00,$85,$84,$09,$21,$09,$21,$09,$20
	.db $83,$00
.ref43:
	.db $88,$5b,$00,$85,$57,$00,$85,$55,$00,$89,$56,$85,$55,$01,$4d,$00
	.db $81
.ref44:
	.db $69,$00,$85,$5b,$00,$85,$5f,$00,$85,$84,$09,$21,$09,$21,$09,$20
	.db $83,$00
	.db $ff,$10
	.dw .ref41
	.db $ff,$11
	.dw .ref42
	.db $ff,$10
	.dw .ref43
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref48:
	.db $00,$bd
.ref49:
	.db $00,$bd
.ref50:
	.db $00,$bd
.ref51:
	.db $00,$bd
.ref52:
	.db $00,$bd
.ref53:
	.db $00,$bd
.ref54:
	.db $00,$bd
.ref55:
	.db $00,$bd
.ref56:
	.db $86,$38,$00,$8b,$38,$00,$8b,$38,$00,$8b,$38,$00,$8b
.ref57:
	.db $38,$00,$8b,$38,$00,$8b,$38,$00,$8b,$38,$00,$8b
	.db $ff,$0c
	.dw .ref57
.ref59:
	.db $38,$00,$8b,$38,$00,$8b,$38,$00,$83,$38,$00,$38,$89,$38,$00,$83
	.db $ff,$0c
	.dw .ref57
	.db $ff,$0c
	.dw .ref57
	.db $ff,$0c
	.dw .ref57
	.db $ff,$10
	.dw .ref59
	.db $ff,$0c
	.dw .ref57
	.db $ff,$0c
	.dw .ref57
	.db $ff,$0c
	.dw .ref57
	.db $ff,$10
	.dw .ref59
	.db $ff,$0c
	.dw .ref57
	.db $ff,$0c
	.dw .ref57
	.db $ff,$0c
	.dw .ref57
	.db $ff,$10
	.dw .ref59
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref72:
	.db $bf
.ref73:
	.db $bf
.ref74:
	.db $bf
.ref75:
	.db $bf
.ref76:
	.db $bf
.ref77:
	.db $bf
.ref78:
	.db $bf
.ref79:
	.db $bf
.ref80:
	.db $bf
.ref81:
	.db $bf
.ref82:
	.db $bf
.ref83:
	.db $bf
.ref84:
	.db $bf
.ref85:
	.db $bf
.ref86:
	.db $bf
.ref87:
	.db $bf
.ref88:
	.db $bf
.ref89:
	.db $bf
.ref90:
	.db $bf
.ref91:
	.db $bf
.ref92:
	.db $bf
.ref93:
	.db $bf
.ref94:
	.db $bf
.ref95:
	.db $bf
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref96:
	.db $bf
.ref97:
	.db $bf
.ref98:
	.db $bf
.ref99:
	.db $bf
.ref100:
	.db $bf
.ref101:
	.db $bf
.ref102:
	.db $bf
.ref103:
	.db $bf
.ref104:
	.db $bf
.ref105:
	.db $bf
.ref106:
	.db $bf
.ref107:
	.db $bf
.ref108:
	.db $bf
.ref109:
	.db $bf
.ref110:
	.db $bf
.ref111:
	.db $bf
.ref112:
	.db $bf
.ref113:
	.db $bf
.ref114:
	.db $bf
.ref115:
	.db $bf
.ref116:
	.db $bf
.ref117:
	.db $bf
.ref118:
	.db $bf
.ref119:
	.db $bf
	.db $fd
	.dw .song0ch4loop
